# Generated by Django 3.2.25 on 2026-01-08 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_department_nationality_student_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.department'),
        ),
    ]
