# Generated by Django 6.0.3 on 2026-03-30 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activeusersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_fingerprint', models.CharField(blank=True, max_length=64)),
                ('otp_generated_at', models.DateTimeField(auto_now_add=True)),
                ('otp_expires_at', models.DateTimeField()),
                ('otp_verified', models.BooleanField(default=False)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('resend_count', models.PositiveIntegerField(default=0)),
                ('last_resend_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'OTP Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('attempt_number', models.PositiveIntegerField()),
                ('success', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, choices=[('INVALID_OTP', 'Invalid OTP'), ('EXPIRED_OTP', 'Expired OTP'), ('CORRECT', 'Correct OTP')], max_length=50)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.otpsession')),
            ],
            options={
                'verbose_name_plural': 'OTP Attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='otpsession',
            index=models.Index(fields=['session_id'], name='core_otpses_session_a3fe55_idx'),
        ),
        migrations.AddIndex(
            model_name='otpsession',
            index=models.Index(fields=['user_email'], name='core_otpses_user_em_9410f1_idx'),
        ),
        migrations.AddIndex(
            model_name='otpsession',
            index=models.Index(fields=['is_active'], name='core_otpses_is_acti_709424_idx'),
        ),
        migrations.AddIndex(
            model_name='otpattempt',
            index=models.Index(fields=['session', 'attempted_at'], name='core_otpatt_session_84ba8d_idx'),
        ),
    ]
