# Generated by Django 3.2.25 on 2026-02-19 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0031_auto_20260219_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_paper',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 19, 17, 22, 13, 210775)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 19, 17, 22, 13, 210775)),
        ),
    ]
