# Generated by Django 4.2.28 on 2026-02-22 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0032_auto_20260219_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 22, 13, 20, 39, 588858)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 22, 13, 20, 39, 588858)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='total_marks',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
