# Generated by Django 6.0.3 on 2026-03-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0041_examsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examfocuslog',
            name='max_focus_losses',
            field=models.IntegerField(default=5),
        ),
    ]
